#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_CARTRIDGE_SDK_BASH

dest_dir=${OPENSHIFT_DATA_DIR}current

current_version=$(cat ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version)
install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${current_version}

data_dir=${OPENSHIFT_DATA_DIR}data

if [ ! -d ${data_dir} ]; then

  auth_conf=${install_dir}/conf/users.auth.php
  admin_pwd=$(generate_password)
  admin_pwd_md5=$(echo -n $admin_pwd | md5sum | cut -d' ' -f1)

  echo "admin:${admin_pwd_md5}:Administrator:example@example.com:admin,user" >> $auth_conf

  client_result ""
  client_result "DokuWiki ${current_version} deployed succesfully."
  client_result ""
  client_result "      Login: admin"
  client_result "   Password: $admin_pwd"
  client_result ""
  client_result "NOTE: Don't forget to change your wiki admin password."
  client_result ""

  mkdir -p ${OPENSHIFT_DATA_DIR}data
  mv ${install_dir}/data/* ${data_dir}/
  rm -rf ${install_dir}/data
fi

if [ ! -d "${dest_dir}" ]; then
  mkdir -p $dest_dir
  cp -rf ${install_dir}/* ${dest_dir}/
fi

# Replace the php/ directory with provided clean Dokuwiki installation
#
if [ -d ${OPENSHIFT_REPO_DIR}php ]; then
  rm -rf ${OPENSHIFT_REPO_DIR}php
fi

ln -sf ${dest_dir} ${OPENSHIFT_REPO_DIR}php
ln -sf ${data_dir} ${OPENSHIFT_REPO_DIR}php/data


