# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 23 Mar 2012 16:38:00 +0000
*               @ALL          1
*               @user         8
